coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        paths: 
          - "src"
        only_pulls: true
    patch: 
      default: 
        target: 80%
        threshold: 1%
        paths:
          - "src" 
        only_pulls: true
