export enum GooglePLayServices {
  PLAY_SERVICES_NOT_AVAILABLE = 'PLAY_SERVICES_NOT_AVAILABLE',
  SIGN_IN_CANCELLED = '12501',
  IN_PROGRESS = 'ASYNC_OP_IN_PROGRESS',
  SIGN_IN_REQUIRED = '4',
  DEVELOPER_ERROR = '10',
}
