name: building-app
on:
  push:
    branches: 
      - main
      - create-new-ci-cd
      - develop
      - homolog 

jobs: 
  check-bats-version: 
    runs-on: ubuntu-20.04
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'
      
      - run: npm install

      - name: run unit test
        run: npm run test

      - name: conditional command
        if: ${{ $GITHUB_REF == 'refs/heads/create-new-ci-cd' }}
        run: echo "${GITHUB_REF}"
    
        
        #echo "${GITHUB_REF}"   
      # contains($GITHUB_REF, 'refs/heads/create-new-ci-cd')
      #- name: create a new release
      #  run: gh release create v1.1.0 --title "v1.1.0"
