name: building-app
on:
  push:
    branches: 
      - main
      - create-new-ci-cd
      - develop
      - homolog 

jobs: 
  check-bats-version: 
    runs-on: ubuntu-20.04
    environment: Environments
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'
      - run: npm install

      - name: run unit test
        run: npm run test


      - name: new release
        env: 
          EC: ${{ secrets.EC }}
          VERSION: 1.2.3
        if: ${{ github.ref_name == 'main' }}
        run: |
          echo "$EC" > .token
          gh auth login  --with-token < .token
          unset EC
          rm -f .token
          gh release create "v$VERSION" --title "$VERSION (test)"


